### ISSUE TITLE
Error in include statement?

### ISSUE THREAD

**Issue by sergiocntr** [arduino-libraries/Arduino_NiclaSenseEnv#7]
I get this error: 
`...\Arduino\libraries\Arduino_NiclaSenseEnv\src/I2CDevice.h:7:10: fatal error: array: No such file or directory 
 #include <array>`

**Comment by per1234** [comment]
Hi @sergiocntr. I'm going to ask you to provide some additional information that might help us to identify the problem.

---

❗ This procedure is not intended to solve the problem. The purpose is to gather more information.

---

Please do this:

1. Select **File > Preferences...** (or **Arduino IDE > Settings...** for macOS users) from the Arduino IDE menus.
   The "**Preferences**" dialog will open.
1. Check the box next to "**Show verbose output during: > ☐ compile**" in the "**Preferences**" dialog.
1. Click the "**OK**" button.
   The "**Preferences**" dialog will close.
1. Select **Sketch > Verify/Compile** from the Arduino IDE menus.
1. Wait for the compilation to fail.
1. You will see a "**Compilation error: ...**" notification at the bottom right corner of the Arduino IDE window. Click the "**COPY ERROR MESSAGES**" button on that notification.
1. [Paste](https://lifehacker.com/how-to-copy-cut-and-paste-for-beginners-5801525) the error messages in a reply here.
   In order to ensure the text is not corrupted, please use [code fencing](https://guides.github.com/features/mastering-markdown/).

**Comment by sergiocntr** [comment]
I opened this issue on behalf of a friend, but after further investigation, it seems the problem lies in the limitations of 8-bit AVR microcontrollers (e.g., constrained RAM, lack of full C++ standard library support, and architectural restrictions) and I'm not able to report all the log messages.

Considering this, I believe the issue can be closed. Thank you for your time and understanding.

Best regards.
